### ISSUE TITLE
ThinkPHP框架特性引发的SQL注入漏洞

### ISSUE THREAD

**Issue by sadk** [top-think/thinkphp#340]
http://www.wooyun.org/bugs/wooyun-2015-0150649

**Comment by liu21st** [comment]
这个当天就已经修复了的~

**Comment by yekz** [comment]
@liu21st 旧的框架如何处理，比如 3.1

**Comment by liu21st** [comment]
@yekz  对比下 github昨天的更新代码，或者等后面详细的说明吧~

**Comment by Boomdawn** [comment]
这个问题是看哪次提交 对比修改？

**Comment by liu21st** [comment]
@Boomdawn  主要参考数据库driver类的parseorder和parselimit方法即可
