### ISSUE TITLE
部署新代码时，需要删除什么文件？

### ISSUE THREAD

**Issue by domainname** [top-think/thinkphp#366]
在将新代码部署到服务器上覆盖老代码的时候，需要删除服务器上的Runtime/Cache目录、Runtime/common*文件，除此之外，还需要删除什么其他目录或文件吗？

我每次部署，总觉得有的cache没删干净，要把APP_DEBUG设置成true跑一阵，似乎才干净了。请指教

**Comment by muxiaokun** [comment]
Runtime/common~runtime.php

**Comment by domainname** [comment]
@muxiaokun Runtime/common~runtime.php，这个已删除了，还有其他需要删除或注意的地方么？

**Comment by muxiaokun** [comment]
不需要了
主要导致错误的是这个文件整合了基础的配置（原意是为了加速程序运行，不要反复读取配置）
貌似模板的缓存是5分钟  我想你5分钟等等也就过去了

**Comment by domainname** [comment]
谢谢！
