### ISSUE TITLE
php5.3.2版本连接mysql乱码

### ISSUE THREAD

**Issue by lifeforfun** [top-think/thinkphp#402]
本来DB_CHARSET还有dsn里都设置了charset了，但是并没有什么卵用，跟踪代码发现mysql连接时确实有做php版本判断，但是对编码这块根本没有处理，全指望dsn里面设置编码，数据库连接之后并没有运行set names语句设置编码。
还好有提供DB_PARAMS可以挽救一下，设置了PDO::MYSQL_ATTR_INIT_COMMAND => 'set names utf8' 然而觉得设置连接时的编码这些工作应该交给框架来做，我们只要通过配置告诉我们想用何种编码就行了，毕竟我们用框架只是想实现单纯的业务逻辑处理，希望官方能够修正

**Comment by lifeforfun** [comment]
提一个和issue无关的建议，本身TP是本着面向对象思想开发的框架，但是框架中无处不在的配置文件却很让人头疼，每个模块都可以有自己的配置，可配置项可以罗列很长一页(虽然大部分不用配置)，而且文档里对所有配置项的讲解也只是点到即止。既然这么多配置项那可想而知框架里肯定各种if判断，估计就连框架开发者都会头晕，而且还会增加BUG风险率，那使用者稍不留意也很容易遇到一些比较费解的问题。
那是否有想过将配置项再抽象画，将配置写入框架类的属性里面？
还有单字母函数用起来真的很别扭，IDE都不能提示参数文档。

**Comment by liu21st** [comment]
这是将来版本的方向~

**Comment by Jaggle** [comment]
> 还有单字母函数用起来真的很别扭，IDE都不能提示参数文档。

我觉得也是
