### ISSUE TITLE
关于PHP版本大于5.3.6, 数据库字段结果int查询的结果string的问题

### ISSUE THREAD

**Issue by sixbyter** [top-think/thinkphp#410]
环境: 
PHP >5.3.6
ThinkPHP > 3.2
有安装mysqlnd

代码
```
$record = M('users')->fields('id')->select();
var_dump($record);
```
结果
```
array (size=2)
  'id' => string '1' (length=1)
```
数据库中, id的类型是inter, 而查询的结果是string. 

原因:/ThinkPHP/Library/Think/Db/Driver.class.php
```
if(version_compare(PHP_VERSION,'5.3.6','<=')){
    // 禁用模拟预处理语句
    $this->options[PDO::ATTR_EMULATE_PREPARES]  =   false;
}
```
虽然有设置 `PDO::ATTR_STRINGIFY_FETCHES =>  false`, 但貌似还需设置 `PDO::ATTR_EMULATE_PREPARES  =>   false`

**Comment by liu21st** [comment]
这块新版数据库类已经处理了
