### ISSUE TITLE
访问目录加上模块名就报错。为什么 

### ISSUE THREAD

**Issue by yangjingjingjing** [top-think/thinkphp#514]
http://localhost/5/index.php/Home/Index/index     报错
http://localhost/5/index.php/Index/index   正确

**Comment by liu21st** [comment]
目测你的服务器配置有问题 检查下 apache是否加上 -Multiviews 参数

**Comment by Amberbaifeng** [comment]
怎么退订？不接收这个邮件 amber.feng 邮箱：amber.feng@aliyun.com 签名由 网易邮箱大师 定制 在2018年01月01日 20:09，ThinkPHP 写道： Closed #514. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
