### ISSUE TITLE
能否将VAR_AUTO_STRING系统参数默认设置为true

### ISSUE THREAD

**Issue by helbing** [top-think/thinkphp#522]
VAR_AUTO_STRING参数的作用是让I方法的自动转为string类型，这个参数默认是为false，能否将它默认设置为true，有不少新手可能不会或者不明白为什么要给I加上变量修饰符，而如果不加是会带来安全问题得到，能否TP官方把它默认设置为true，也避免一些新手写的程序有安全上的漏洞

**Comment by liu21st** [comment]
3.2版本已经过了维护和安全更新周期，官方不会提交任何修改及发布新版本了。因为官方不再更新，所以由官方更改和项目自己更改核心本质上已经没区别了。
