### ISSUE TITLE
路由：匹配规则是从前向后匹配，导致有些路由匹配不到

### ISSUE THREAD

**Issue by meiyoufengzhengdexian** [top-think/thinkphp#526]
路由文件：
```
Route::get('news', 'index/testController/test1');

Route::get('news_detail', 'index/testController/test2');
```
控制器
```
    public function test1()
    {
        echo 'new';
    }
    public function test2()
    {
        echo 'news_detail';
    }
```
当访问` /news_detail`的时候 会匹配到` /new` 的路由， 这使一个刚刚接触，没有仔细阅读文档的开发人员
十脸懵逼。。。

在`RuleItem.php`第 248 行左右

`if (0 === strcasecmp($rule, $url) ||
 (!$completeMatch && 0 === strncasecmp($rule, $url, strlen($rule)))) 
{
    return $var;
}`

改成
`if (0 === strcasecmp($rule, $url) ||
 (!$completeMatch && rule == $url )) 
{
    return $var;
}` 后解决。

**Comment by oyvfhp** [comment]
确实，不只是这个问题

Route::group('blog', function(){
    // Blog/ask （这里有点无语，不放前面会与 / 冲突）
    Route::get('ask', 'blog/ask.Index/index');

    Route::get('hello/<name>', 'blog/Index/hello'); 

    // Blog首页
    Route::get('/', 'blog/Index/index');
    
    

})

同样的问题，如果把 ask 放后面 就直接解析到 // Blog首页 去了

**Comment by meiyoufengzhengdexian** [comment]
@oyvfhp  此问题已301重定向到此 [https://github.com/top-think/think/issues/823](url)

**Comment by liu21st** [comment]
这是一个是否完整路由匹配的问题 严格的话就设置开启完整匹配
