### ISSUE TITLE
3.2.5 最新版排序问题

### ISSUE THREAD

**Issue by hhrensheng** [top-think/thinkphp#533]
当给表定义别名的等情况下 调用order等排序方法，最终会解析为类似于 
![image](https://user-images.githubusercontent.com/29398035/47699987-b743c880-dc4f-11e8-8a82-b69c318d55f5.png)

 的语句。导致报Unknown column 'A.id'的错误

**Comment by liu21st** [comment]
改进了下，你可以用开发版重新测试下

**Comment by hhrensheng** [comment]
> 改进了下，你可以用开发版重新测试下

出现个问题，就是用list赋值之后，传给parseKey方法，parseKey方法会报错 打印变量为空。php环境5.6

**Comment by hhrensheng** [comment]
> 改进了下，你可以用开发版重新测试下

而且同理，当调用count等统计方法的时候，也会因为`*`的问题报错

**Comment by liu21st** [comment]
可以了

**Comment by hhrensheng** [comment]
> 可以了

ok 没问题了，十分感谢
