### ISSUE TITLE
count语句报错

### ISSUE THREAD

**Issue by hepeichun** [top-think/thinkphp#541]
![qq 20181228145828](https://user-images.githubusercontent.com/13855247/50505909-19cf0e80-0ab1-11e9-8bcd-79cfe412806d.png)

count语句在*号时不应该加单引号

**Comment by hepeichun** [comment]
ThinkPHP/Library/Think/Model.class.php 文件的241行修改成下面的代码解决

$field = isset($args[0]) ? $this->db->parseKey($args[0], true) : '*';

return $this->getField(strtoupper($method) . '(' . $field . ') AS tp_' . $method);

**Comment by liu21st** [comment]
你是最新版本么？

**Comment by hepeichun** [comment]
> 你是最新版本么？

是的

**Comment by hepeichun** [comment]
> 你是最新版本么？

换成master版本貌似没有复现。稍等这在测试一下。

**Comment by hepeichun** [comment]
master版本是没问题的，看到修复了，谢谢
