### ISSUE TITLE
刚发现，thinkphp 不管是3.x版本还是5.x 最新版本，url参数只要有s= 就会出现报错

### ISSUE THREAD

**Issue by helays** [top-think/thinkphp#545]
最近发现一个BUG，不知道i故意为之还是真的BUG，URL参数 比如这样 www.demo.com?s=123 ，
只要参数里面有s= 就会报错。跟踪发现 当有s 的时候，contorller 是 index。

**Comment by liu21st** [comment]
s参数是系统默认的兼容模式pathinfo变量，如果有冲突的话 你需要配置更改var_pathinfo参数的值
